<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[22]=array(19,1,1,'576O5a655YeP6IKl');
$cfg_Cs[21]=array(19,1,1,'5YGl5bq36aWu6aOf');
$cfg_Cs[20]=array(19,1,1,'5Lit6I2v5L+d5YGl');
$cfg_Cs[19]=array(0,1,1,'55+l6K+G5a2m5aCC');
$cfg_Cs[17]=array(15,1,1,'5biC5Zy65b+r6K6v');
$cfg_Cs[18]=array(15,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[16]=array(15,1,1,'6I2v5biC5Yqo5oCB');
$cfg_Cs[15]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[14]=array(0,1,1,'6K6i5Y2V5p+l6K+i');
$cfg_Cs[13]=array(0,1,1,'5ZCI5L2c5ZWG5LyB');
$cfg_Cs[12]=array(0,1,1,'5Lqn5ZOB5bGV56S6');
$cfg_Cs[23]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[24]=array(23,1,1,'5biu5Yqp5Lit5b+D');
?>